### ISSUE TITLE
Request: Wild Card Character for in search, ie "+" and "#", as used in other mqtt subscribe operations

### ISSUE THREAD

**Issue by wa0uwh** [adamoutler/mqtt-explorer#5]
Will we every have the "+" character available for Mqtt Explorer search field? 

I think the trailing "#" is implied with Mqtt Explorer.

Thanks for your efforts.

**Comment by adamoutler** [comment]
This project is deprecated. The developer of the official package has released it. I am just packaging the docker for home assistant.
